[[team]]
name = "Laura Janda"
picture = "janda.jpg"
homepage = "http://ansatte.uit.no/laura.janda/"

[[team]]
name = "Marte Aasen"
picture = "aasen.jpg"
homepage = "https://www.prosjektutsyn.no/om-utsyn/"

[[team]]
name = "Radovan Bast"
picture = "bast.jpg"
homepage = "https://bast.fr"

[[team]]
name = "Vladimír Benko"
picture = "benko.jpg"
homepage = "http://www.juls.savba.sk/~vladob"

[[team]]
name = "Václav Cvrček"
picture = "cvrcek.jpg"
homepage = "https://ucnk.ff.cuni.cz/cs/ustav/lide/vaclav-cvrcek/"

[[team]]
name = "Isabel Dineen"
picture = "dineen.jpg"
homepage = "https://en.uit.no/ansatte/person?p_document_id=724834"

[[team]]
name = "Jakub M. Godzimirski"
picture = "godzimirski.jpg"
homepage = "https://www.nupi.no/en/About-NUPI/Employees/Researchers/Jakub-M.-Godzimirski"

[[team]]
name = "Gunhild Hoogensen Gjørv"
picture = "hoogensen-gjoerv.jpg"
homepage = "https://uit.no/ansatte/person?p_document_id=42266"

[[team]]
name = "Mariia Kobzeva"
picture = "kobzeva.jpg"
homepage = "https://en.uit.no/ansatte/person?p_document_id=649306"

[[team]]
name = "Anastasia Makarova"
picture = "makarova.jpg"
homepage = "https://katalog.uu.se/profile/?id=N20-1741"

[[team]]
name = "Tore Nesset"
picture = "nesset.jpg"
homepage = "https://uit.no/ansatte/person?p_document_id=41533"

[[team]]
name = "Anna Obukhova"
picture = "obukhova.jpg"
homepage = "https://en.uit.no/ansatte/person?p_document_id=727362&p_dimension_id=210121"

[[team]]
name = "Holger Pötzsch"
picture = "poetzsch.jpg"
homepage = "https://uit.no/ansatte/person?p_document_id=43820"

[[team]]
name = "Andrei Rogatchevski"
picture = "rogatchevski.jpg"
homepage = "https://uit.no/ansatte/person?p_document_id=361780"

[[team]]
name = "Josef Šlerka"
picture = "slerka.jpg"
homepage = "https://uisk.ff.cuni.cz/cs/o-ustavu/vyucujici/josef-slerka/"

[[team]]
name = "Trond Trosterud"
picture = "trosterud.jpg"
homepage = "https://uit.no/ansatte/person?p_document_id=41545"

[[team]]
name = "Masako Ueda Fidler"
picture = "ueda-fidler.jpg"
homepage = "https://vivo.brown.edu/display/mufidler"

[[team]]
name = "Julie Wilhelmsen"
picture = "wilhelmsen.jpg"
homepage = "https://www.nupi.no/Om-NUPI/Medarbeidere/Forskere/Julie-Wilhelmsen"

[[team]]
name = "Valentina Zhukova"
picture = "zhukova.jpg"
homepage = "https://en.uit.no/ansatte/person?p_document_id=750196&p_dimension_id=210121"
